[package]
name = "orx-fixed-vec"
version = "1.0.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An efficient fixed capacity vector with pinned elements."
license = "MIT"
repository = "https://github.com/orxfun/orx-fixed-vec/"
keywords = ["vec", "pinned", "array", "split", "fixed"]
categories = ["data-structures"]

[dependencies]
orx-pinned-vec = "1.0"

[[bench]]
name = "random_access"
harness = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.8"
rand_chacha = "0.3"
