[package]
name = "orx-fixed-vec"
version = "0.4.3"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "A fixed capacity vector with pinned elements."
license = "MIT"
repository = "https://github.com/orxfun/orx-fixed-vec/"
keywords = ["vec", "pinned", "array", "split", "fixed"]
categories = ["data-structures"]

[dependencies]
orx-pinned-vec = "0.5.1"
