[package]
name = "demo_parallelization"
version = "0.1.0"
edition = "2024"
publish = ["artifactory"]

[dependencies]
orx-fixed-vec = { path = "../../../orx-fixed-vec" }
orx-parallel = { version = "3.2.0", default-features = false }
